<?php
require_once 'db.php';
requireLogin();

$category   = $_GET['category'] ?? 'all';
$startDate  = $_GET['start_date'] ?? '';
$endDate    = $_GET['end_date'] ?? '';
$sexFilter  = $_GET['sex'] ?? 'all';
$stageFilter= $_GET['stage'] ?? 'all';
$sourceFilter= $_GET['source'] ?? 'all';

logActivity($pdo, 'report_exported', "Exported official CSV farm report for category '" . ucfirst($category) . "'");

$filename = "Msantha_Farm_Report_" . ucfirst($category) . "_" . date('Y-m-d') . ".csv";

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

$output = fopen('php://output', 'w');

// Output Header Info
fputcsv($output, ['MSANTHA INVESTMENTS AND GENERAL SUPPLIERS (MIGS)']);
fputcsv($output, ['OFFICIAL FARM REPORT - ' => strtoupper($category)]);
fputcsv($output, ['Generated Date:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By:', $_SESSION['user_fullname'] ?? 'System User']);
if ($startDate || $endDate) {
    fputcsv($output, ['Date Range Filter:', ($startDate ?: 'Beginning') . ' to ' . ($endDate ?: 'Present')]);
}
if ($sourceFilter !== 'all') {
    fputcsv($output, ['Origin / Source Filter:', $sourceFilter]);
}
fputcsv($output, []); // Blank separator line

if ($category === 'inventory' || $category === 'all') {
    fputcsv($output, ['--- PIG INVENTORY REPORT ---']);
    fputcsv($output, ['ID', 'Tag No', 'Source / Origin', 'Sex', 'Stage', 'Breed', 'Date of Birth', 'Sire', 'Dam', 'Status']);
    
    $where = ["1=1"];
    $params = [];
    if ($sexFilter !== 'all') { $where[] = "sex = ?"; $params[] = $sexFilter; }
    if ($stageFilter !== 'all') { $where[] = "stage = ?"; $params[] = $stageFilter; }
    if ($sourceFilter !== 'all') { $where[] = "source = ?"; $params[] = $sourceFilter; }
    
    $sql = "SELECT id, tag_no, source, sex, stage, breed, dob, sire, dam, status FROM pigs WHERE " . implode(' AND ', $where) . " ORDER BY id DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['tag_no'],
            $row['source'] ?: 'Born on Farm',
            $row['sex'],
            ucfirst($row['stage']),
            $row['breed'],
            $row['dob'],
            $row['sire'] ?: 'N/A',
            $row['dam'] ?: 'N/A',
            ucfirst($row['status'])
        ]);
    }
    fputcsv($output, []);
}

if ($category === 'external' || $category === 'all') {
    fputcsv($output, ['--- EXTERNAL / PURCHASED PIGS ACQUISITION AUDIT ---']);
    fputcsv($output, ['ID', 'Tag No', 'Sex', 'Stage', 'Breed', 'Date of Birth', 'Sire', 'Dam', 'Status']);
    
    $where = ["source = 'External Purchase'"];
    $params = [];
    if ($sexFilter !== 'all') { $where[] = "sex = ?"; $params[] = $sexFilter; }
    if ($stageFilter !== 'all') { $where[] = "stage = ?"; $params[] = $stageFilter; }
    
    $sql = "SELECT id, tag_no, sex, stage, breed, dob, sire, dam, status FROM pigs WHERE " . implode(' AND ', $where) . " ORDER BY id DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['tag_no'],
            $row['sex'],
            ucfirst($row['stage']),
            $row['breed'],
            $row['dob'],
            $row['sire'] ?: 'N/A',
            $row['dam'] ?: 'N/A',
            ucfirst($row['status'])
        ]);
    }
    fputcsv($output, []);
}

if ($category === 'sales' || $category === 'all') {
    fputcsv($output, ['--- SALES & REVENUE LEDGER ---']);
    fputcsv($output, ['ID', 'Date', 'Type', 'Reference ID', 'Weight (kg)', 'Buyer Details', 'Amount (MWK)', 'Remarks']);
    
    $where = ["1=1"];
    $params = [];
    if (!empty($startDate)) { $where[] = "date >= ?"; $params[] = $startDate; }
    if (!empty($endDate)) { $where[] = "date <= ?"; $params[] = $endDate; }
    
    $sql = "SELECT * FROM sales WHERE " . implode(' AND ', $where) . " ORDER BY date DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['date'],
            str_replace('_', ' ', ucfirst($row['type'])),
            $row['reference_id'] ?: 'N/A',
            $row['weight'] ?: 'N/A',
            $row['buyer_info'] ?: 'Cash Customer',
            number_format($row['amount'], 2, '.', ''),
            $row['remarks']
        ]);
    }
    fputcsv($output, []);
}

if ($category === 'breeding' || $category === 'all') {
    fputcsv($output, ['--- BREEDING & PREGNANCY AUDIT ---']);
    fputcsv($output, ['ID', 'Sow Tag', 'Service Date', 'Sire Tag', 'Expected Farrowing', 'Actual Farrowing', 'Total Born', 'Born Alive', 'Stillborn', 'Avg Weaning Wt (kg)', 'Status']);
    
    $where = ["1=1"];
    $params = [];
    if (!empty($startDate)) { $where[] = "b.date_of_service >= ?"; $params[] = $startDate; }
    if (!empty($endDate)) { $where[] = "b.date_of_service <= ?"; $params[] = $endDate; }
    
    $sql = "SELECT b.*, p.tag_no FROM breeding_records b JOIN pigs p ON b.pig_id = p.id WHERE " . implode(' AND ', $where) . " ORDER BY b.date_of_service DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['tag_no'],
            $row['date_of_service'],
            $row['sire_no'] ?: 'N/A',
            $row['expected_farrowing'],
            $row['actual_farrowing'] ?: 'Pending',
            $row['total_born'] ?? 'N/A',
            $row['born_alive'] ?? 'N/A',
            $row['stillborn'] ?? 'N/A',
            $row['avg_weaning_wt'] ?? 'N/A',
            ucfirst($row['status'])
        ]);
    }
    fputcsv($output, []);
}

if ($category === 'vaccination' || $category === 'all') {
    fputcsv($output, ['--- HEALTH & VACCINATION LOGS ---']);
    fputcsv($output, ['ID', 'Date', 'Pig Tag', 'Vaccine', 'Dose', 'Route', 'Administered By', 'Remarks']);
    
    $where = ["1=1"];
    $params = [];
    if (!empty($startDate)) { $where[] = "v.date >= ?"; $params[] = $startDate; }
    if (!empty($endDate)) { $where[] = "v.date <= ?"; $params[] = $endDate; }
    
    $sql = "SELECT v.*, p.tag_no FROM vaccination_records v JOIN pigs p ON v.pig_id = p.id WHERE " . implode(' AND ', $where) . " ORDER BY v.date DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['date'],
            $row['tag_no'],
            $row['vaccine'],
            $row['dose'] ?: 'N/A',
            $row['route'] ?: 'N/A',
            $row['administered_by'] ?: 'Staff',
            $row['remarks']
        ]);
    }
    fputcsv($output, []);
}

if ($category === 'mortality' || $category === 'all') {
    fputcsv($output, ['--- MORTALITY & LOSS AUDIT ---']);
    fputcsv($output, ['ID', 'Date', 'Pig Tag', 'Cause of Death', 'Remarks']);
    
    $where = ["1=1"];
    $params = [];
    if (!empty($startDate)) { $where[] = "m.date >= ?"; $params[] = $startDate; }
    if (!empty($endDate)) { $where[] = "m.date <= ?"; $params[] = $endDate; }
    
    $sql = "SELECT m.*, p.tag_no FROM mortality m JOIN pigs p ON m.pig_id = p.id WHERE " . implode(' AND ', $where) . " ORDER BY m.date DESC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    
    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['date'],
            $row['tag_no'],
            $row['cause'] ?: 'Unspecified',
            $row['remarks']
        ]);
    }
}

fclose($output);
exit();
