<?php
require_once 'db.php';
requireLogin();

// Filter parameters
$actionGroup = $_GET['action_group'] ?? 'all';
$selectedAction = $_GET['action'] ?? 'all';
$selectedUser  = $_GET['user'] ?? 'all';
$startDate     = $_GET['start_date'] ?? '';
$endDate       = $_GET['end_date'] ?? '';
$searchQuery   = trim($_GET['q'] ?? '');

// Handle CSV Export of Activity Logs
if (isset($_GET['export']) && $_GET['export'] === 'csv') {
    logActivity($pdo, 'report_exported', "Exported System Activity Audit Logs to CSV");

    $filename = "Msantha_Activity_Logs_" . date('Y-m-d_His') . ".csv";
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');

    $output = fopen('php://output', 'w');
    fputcsv($output, ['MSANTHA INVESTMENTS AND GENERAL SUPPLIERS (MIGS)']);
    fputcsv($output, ['SYSTEM ACTIVITY AUDIT LOG REPORT']);
    fputcsv($output, ['Generated Date:', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated By:', $_SESSION['user_fullname'] ?? 'System User']);
    fputcsv($output, []); // Blank line

    fputcsv($output, ['Log ID', 'Timestamp', 'Username', 'Role', 'Action Type', 'Description', 'IP Address']);

    $where = ["1=1"];
    $params = [];

    if ($actionGroup !== 'all') {
        if ($actionGroup === 'auth') {
            $where[] = "action IN ('login', 'logout', 'login_failed')";
        } else if ($actionGroup === 'pigs') {
            $where[] = "action IN ('pig_created', 'pig_updated', 'pig_status_changed')";
        } else if ($actionGroup === 'health') {
            $where[] = "action IN ('growth_added', 'vaccination_added')";
        } else if ($actionGroup === 'breeding') {
            $where[] = "action IN ('breeding_added')";
        } else if ($actionGroup === 'users') {
            $where[] = "action IN ('user_created', 'user_updated', 'profile_updated', 'password_changed')";
        } else if ($actionGroup === 'exports') {
            $where[] = "action IN ('report_exported')";
        }
    }

    if ($selectedAction !== 'all') {
        $where[] = "action = ?";
        $params[] = $selectedAction;
    }

    if ($selectedUser !== 'all') {
        $where[] = "username = ?";
        $params[] = $selectedUser;
    }

    if (!empty($startDate)) {
        $where[] = "DATE(created_at) >= ?";
        $params[] = $startDate;
    }

    if (!empty($endDate)) {
        $where[] = "DATE(created_at) <= ?";
        $params[] = $endDate;
    }

    if (!empty($searchQuery)) {
        $where[] = "(description LIKE ? OR username LIKE ? OR ip_address LIKE ?)";
        $searchTerm = "%$searchQuery%";
        $params[] = $searchTerm;
        $params[] = $searchTerm;
        $params[] = $searchTerm;
    }

    $exportSql = "SELECT * FROM activity_logs WHERE " . implode(' AND ', $where) . " ORDER BY id DESC";
    $exportStmt = $pdo->prepare($exportSql);
    $exportStmt->execute($params);

    while ($row = $exportStmt->fetch(PDO::FETCH_ASSOC)) {
        fputcsv($output, [
            $row['id'],
            $row['created_at'],
            $row['username'],
            ucfirst($row['user_role']),
            $row['action'],
            $row['description'],
            $row['ip_address']
        ]);
    }
    exit();
}

// KPI Metrics
$totalLogsCount = $pdo->query("SELECT COUNT(*) FROM activity_logs")->fetchColumn();
$todayLogsCount = $pdo->query("SELECT COUNT(*) FROM activity_logs WHERE DATE(created_at) = CURDATE()")->fetchColumn();
$activeUsersToday = $pdo->query("SELECT COUNT(DISTINCT username) FROM activity_logs WHERE DATE(created_at) = CURDATE()")->fetchColumn();
$failedLoginsCount = $pdo->query("SELECT COUNT(*) FROM activity_logs WHERE action = 'login_failed'")->fetchColumn();

// Fetch distinct usernames for filter dropdown
$userList = $pdo->query("SELECT DISTINCT username FROM activity_logs ORDER BY username ASC")->fetchAll(PDO::FETCH_COLUMN);

// Build Main Query
$where = ["1=1"];
$params = [];

if ($actionGroup !== 'all') {
    if ($actionGroup === 'auth') {
        $where[] = "action IN ('login', 'logout', 'login_failed')";
    } else if ($actionGroup === 'pigs') {
        $where[] = "action IN ('pig_created', 'pig_updated', 'pig_status_changed')";
    } else if ($actionGroup === 'health') {
        $where[] = "action IN ('growth_added', 'vaccination_added')";
    } else if ($actionGroup === 'breeding') {
        $where[] = "action IN ('breeding_added')";
    } else if ($actionGroup === 'users') {
        $where[] = "action IN ('user_created', 'user_updated', 'profile_updated', 'password_changed')";
    } else if ($actionGroup === 'exports') {
        $where[] = "action IN ('report_exported')";
    }
}

if ($selectedAction !== 'all') {
    $where[] = "action = ?";
    $params[] = $selectedAction;
}

if ($selectedUser !== 'all') {
    $where[] = "username = ?";
    $params[] = $selectedUser;
}

if (!empty($startDate)) {
    $where[] = "DATE(created_at) >= ?";
    $params[] = $startDate;
}

if (!empty($endDate)) {
    $where[] = "DATE(created_at) <= ?";
    $params[] = $endDate;
}

if (!empty($searchQuery)) {
    $where[] = "(description LIKE ? OR username LIKE ? OR ip_address LIKE ?)";
    $searchTerm = "%$searchQuery%";
    $params[] = $searchTerm;
    $params[] = $searchTerm;
    $params[] = $searchTerm;
}

$sql = "SELECT * FROM activity_logs WHERE " . implode(' AND ', $where) . " ORDER BY id DESC LIMIT 200";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$logs = $stmt->fetchAll();

// Badge & Icon Formatting Helper
function getActionBadgeHTML($action) {
    switch ($action) {
        case 'login':
            return '<span class="badge" style="background: #E8F5E9; color: #2E7D32; font-weight: 600;">🔑 Login</span>';
        case 'logout':
            return '<span class="badge" style="background: #ECEFF1; color: #455A64; font-weight: 600;">🚪 Logout</span>';
        case 'login_failed':
            return '<span class="badge" style="background: #FFEBEE; color: #C62828; font-weight: 600;">⚠️ Failed Login</span>';
        case 'pig_created':
            return '<span class="badge" style="background: #E8F5E9; color: #1B5E20; font-weight: 600;">🐷 Pig Registered</span>';
        case 'pig_updated':
            return '<span class="badge" style="background: #FFF8E1; color: #F57F17; font-weight: 600;">✏️ Pig Updated</span>';
        case 'pig_status_changed':
            return '<span class="badge" style="background: #FFF3E0; color: #E65100; font-weight: 600;">🔄 Status Change</span>';
        case 'growth_added':
            return '<span class="badge" style="background: #E1F5FE; color: #0288D1; font-weight: 600;">⚖️ Weight Logged</span>';
        case 'vaccination_added':
            return '<span class="badge" style="background: #E0F2F1; color: #00695C; font-weight: 600;">💉 Health Logged</span>';
        case 'breeding_added':
            return '<span class="badge" style="background: #FCE4EC; color: #C2185B; font-weight: 600;">🍼 Breeding Logged</span>';
        case 'user_created':
            return '<span class="badge" style="background: #EDE7F6; color: #512DA8; font-weight: 600;">👤 User Created</span>';
        case 'user_updated':
            return '<span class="badge" style="background: #EDE7F6; color: #512DA8; font-weight: 600;">⚙️ User Updated</span>';
        case 'profile_updated':
            return '<span class="badge" style="background: #E8EAF6; color: #303F9F; font-weight: 600;">👤 Profile Updated</span>';
        case 'password_changed':
            return '<span class="badge" style="background: #E8EAF6; color: #303F9F; font-weight: 600;">🔒 Password Changed</span>';
        case 'report_exported':
            return '<span class="badge" style="background: #E0F7FA; color: #0097A7; font-weight: 600;">📥 Report Exported</span>';
        default:
            return '<span class="badge" style="background: #F5F5F5; color: #616161; font-weight: 600;">' . htmlspecialchars($action) . '</span>';
    }
}

include 'includes/header.php';
?>

<div class="dashboard-wrapper">
    <div class="dashboard-header" style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px;">
        <div>
            <h2>System Activity Audit Logs</h2>
            <p>Real-time system audit trial tracking user logins, inventory events, health records, breeding, and security updates.</p>
        </div>
        <a href="logs.php?<?php echo http_build_query(array_merge($_GET, ['export' => 'csv'])); ?>" class="btn btn-primary" style="display: flex; align-items: center; gap: 6px;">
            <span>📥 Export Logs to CSV</span>
        </a>
    </div>

    <!-- KPI Summary Cards -->
    <div class="kpi-container" style="margin-bottom: 20px;">
        <div class="kpi-card kpi-total">
            <div class="kpi-icon">📜</div>
            <div class="kpi-details">
                <h3>Total Activity Logs</h3>
                <p class="kpi-value"><?php echo number_format($totalLogsCount); ?></p>
            </div>
        </div>
        <div class="kpi-card kpi-males">
            <div class="kpi-icon">⚡</div>
            <div class="kpi-details">
                <h3>Today's Activities</h3>
                <p class="kpi-value"><?php echo number_format($todayLogsCount); ?></p>
            </div>
        </div>
        <div class="kpi-card kpi-females">
            <div class="kpi-icon">👥</div>
            <div class="kpi-details">
                <h3>Active Users Today</h3>
                <p class="kpi-value"><?php echo number_format($activeUsersToday); ?></p>
            </div>
        </div>
        <div class="kpi-card" style="border-left-color: #D32F2F;">
            <div class="kpi-icon">🛡️</div>
            <div class="kpi-details">
                <h3>Failed Login Alerts</h3>
                <p class="kpi-value" style="color: <?php echo $failedLoginsCount > 0 ? '#C62828' : 'var(--text-main)'; ?>;"><?php echo number_format($failedLoginsCount); ?></p>
            </div>
        </div>
    </div>

    <!-- Filter Toolbar -->
    <div class="card" style="margin-bottom: 20px; padding: 1.2rem 1.5rem;">
        <form method="GET" action="logs.php" style="display: flex; gap: 15px; align-items: flex-end; flex-wrap: wrap;">
            <div>
                <label style="font-size: 0.85rem; font-weight: 600; margin-bottom: 4px; display: block;">Category Group:</label>
                <select name="action_group" class="form-control" onchange="this.form.submit()" style="padding: 0.45rem 0.8rem; font-size: 0.9rem; min-width: 170px;">
                    <option value="all" <?php echo $actionGroup === 'all' ? 'selected' : ''; ?>>All Activity Categories</option>
                    <option value="auth" <?php echo $actionGroup === 'auth' ? 'selected' : ''; ?>>🔑 Authentication (Logins/Logouts)</option>
                    <option value="pigs" <?php echo $actionGroup === 'pigs' ? 'selected' : ''; ?>>🐷 Pig Inventory Events</option>
                    <option value="health" <?php echo $actionGroup === 'health' ? 'selected' : ''; ?>>💉 Health & Growth Records</option>
                    <option value="breeding" <?php echo $actionGroup === 'breeding' ? 'selected' : ''; ?>>🍼 Breeding Events</option>
                    <option value="users" <?php echo $actionGroup === 'users' ? 'selected' : ''; ?>>⚙️ User & Profile Management</option>
                    <option value="exports" <?php echo $actionGroup === 'exports' ? 'selected' : ''; ?>>📥 Reports & CSV Exports</option>
                </select>
            </div>

            <div>
                <label style="font-size: 0.85rem; font-weight: 600; margin-bottom: 4px; display: block;">Filter User:</label>
                <select name="user" class="form-control" onchange="this.form.submit()" style="padding: 0.45rem 0.8rem; font-size: 0.9rem; min-width: 140px;">
                    <option value="all">All System Users</option>
                    <?php foreach ($userList as $u): ?>
                        <option value="<?php echo htmlspecialchars($u); ?>" <?php echo $selectedUser === $u ? 'selected' : ''; ?>>
                            <?php echo htmlspecialchars($u); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div>
                <label style="font-size: 0.85rem; font-weight: 600; margin-bottom: 4px; display: block;">Start Date:</label>
                <input type="date" name="start_date" class="form-control" value="<?php echo htmlspecialchars($startDate); ?>" style="padding: 0.4rem 0.8rem; font-size: 0.9rem;">
            </div>

            <div>
                <label style="font-size: 0.85rem; font-weight: 600; margin-bottom: 4px; display: block;">End Date:</label>
                <input type="date" name="end_date" class="form-control" value="<?php echo htmlspecialchars($endDate); ?>" style="padding: 0.4rem 0.8rem; font-size: 0.9rem;">
            </div>

            <div style="flex: 1; min-width: 200px;">
                <label style="font-size: 0.85rem; font-weight: 600; margin-bottom: 4px; display: block;">Search Keyword:</label>
                <input type="text" name="q" class="form-control" placeholder="Search in description, username, IP..." value="<?php echo htmlspecialchars($searchQuery); ?>" style="padding: 0.4rem 0.8rem; font-size: 0.9rem;">
            </div>

            <div style="display: flex; gap: 8px;">
                <button type="submit" class="btn btn-primary" style="padding: 0.45rem 1rem; font-size: 0.85rem;">Filter Logs</button>
                <a href="logs.php" class="btn btn-outline" style="padding: 0.45rem 1rem; font-size: 0.85rem;">Reset</a>
            </div>
        </form>
    </div>

    <!-- Logs Table -->
    <div class="table-wrapper">
        <table class="data-table striped">
            <thead>
                <tr>
                    <th style="width:150px;">Date &amp; Time</th>
                    <th style="width:160px;">User &amp; Role</th>
                    <th style="width:175px;">Action Type</th>
                    <th>Activity Description</th>
                    <th style="width:130px;">IP Address</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($logs as $log): ?>
                    <tr>
                        <td style="white-space: nowrap;">
                            <strong><?php echo date('Y-m-d', strtotime($log['created_at'])); ?></strong>
                            <span class="tbl-sub" style="font-family: monospace;"><?php echo date('H:i:s', strtotime($log['created_at'])); ?></span>
                        </td>
                        <td>
                            <strong><?php echo htmlspecialchars($log['username']); ?></strong>
                            <span class="tbl-sub">
                                <span class="tbl-badge <?php echo $log['user_role'] === 'admin' ? 'blue' : 'purple'; ?>" style="font-size:0.7rem;">
                                    <?php echo ucfirst(htmlspecialchars($log['user_role'])); ?>
                                </span>
                            </span>
                        </td>
                        <td><?php echo getActionBadgeHTML($log['action']); ?></td>
                        <td style="line-height: 1.5;"><?php echo htmlspecialchars($log['description']); ?></td>
                        <td style="font-family: monospace; font-size: 0.82rem; color: #666;">
                            <?php echo htmlspecialchars($log['ip_address'] ?: '127.0.0.1'); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>

                <?php if (count($logs) === 0): ?>
                    <tr class="tbl-empty">
                        <td colspan="5">
                            <div style="font-size: 2rem; margin-bottom: 0.5rem;">🔍</div>
                            No system activity logs match your selected search criteria.
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include 'includes/footer.php'; ?>
